# coding: utf-8

"""
    Maxpanda API V1

    The Maxpanda API documentation for version 1  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.update_part_model import UpdatePartModel  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdatePartModel(unittest.TestCase):
    """UpdatePartModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdatePartModel(self):
        """Test UpdatePartModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_part_model.UpdatePartModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
