# coding: utf-8

"""
    Maxpanda API V1

    The Maxpanda API documentation for version 1  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.location_type_response_model import LocationTypeResponseModel  # noqa: E501
from swagger_client.rest import ApiException


class TestLocationTypeResponseModel(unittest.TestCase):
    """LocationTypeResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocationTypeResponseModel(self):
        """Test LocationTypeResponseModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.location_type_response_model.LocationTypeResponseModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
