# coding: utf-8

"""
    Maxpanda API V1

    The Maxpanda API documentation for version 1  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.po_template import POTemplate  # noqa: E501
from swagger_client.rest import ApiException


class TestPOTemplate(unittest.TestCase):
    """POTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPOTemplate(self):
        """Test POTemplate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.po_template.POTemplate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
