# coding: utf-8

"""
    Maxpanda API V1

    The Maxpanda API documentation for version 1  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.create_task_model import CreateTaskModel  # noqa: E501
from swagger_client.rest import ApiException


class TestCreateTaskModel(unittest.TestCase):
    """CreateTaskModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateTaskModel(self):
        """Test CreateTaskModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.create_task_model.CreateTaskModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
