# coding: utf-8

"""
    Maxpanda API V1

    The Maxpanda API documentation for version 1  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.task_status_api_list_model import TaskStatusAPIListModel  # noqa: E501
from swagger_client.rest import ApiException


class TestTaskStatusAPIListModel(unittest.TestCase):
    """TaskStatusAPIListModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskStatusAPIListModel(self):
        """Test TaskStatusAPIListModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.task_status_api_list_model.TaskStatusAPIListModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
