# coding: utf-8

"""
    Maxpanda API V1

    The Maxpanda API documentation for version 1  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.update_task_field import UpdateTaskField  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateTaskField(unittest.TestCase):
    """UpdateTaskField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateTaskField(self):
        """Test UpdateTaskField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_task_field.UpdateTaskField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
