# coding: utf-8

"""
    Maxpanda API V1

    The Maxpanda API documentation for version 1  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.asset_audit_model import AssetAuditModel  # noqa: E501
from swagger_client.rest import ApiException


class TestAssetAuditModel(unittest.TestCase):
    """AssetAuditModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetAuditModel(self):
        """Test AssetAuditModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.asset_audit_model.AssetAuditModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
